import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
  test: {
    include: [
      'test/db/postgres-migration-sanity.test.ts',
      'test/db/schema-parity.test.ts',
      'test/console-contract.test.ts',
      'test/github-oauth.test.ts',
      'test/mcp-service-tools.test.ts',
      'test/notifications-routes-ssrf.test.ts',
      'test/tool-registry.test.ts',
      'test/auth/google-oauth.test.ts',
      'test/auth/token-refresh.test.ts',
      'test/contract/system-routes-services.test.ts',
      'test/llm/agent-pool.test.ts',
      'test/llm/llm-circuit-breaker.test.ts',
      'test/llm/transparency-extract-usage.test.ts',
      'test/llm/model-registry*.test.ts',
      'test/mcp/client-manager-ssrf.test.ts',
      'test/mcp/composite-routing*.test.ts',
      'test/mcp/composite-tool-registry.test.ts',
      'test/mcp/managed-service-rename.test.ts',
      'test/mcp/mode-switching.test.ts',
      'test/mcp/session-heartbeat.test.ts',
      'test/mcp/tool-registry-snapshot.test.ts',
      'test/monitor/ops-agent.test.ts',
      'test/monitor/ops-alerting.test.ts',
      'test/monitor/ops-config-resolver.test.ts',
      'test/monitor/ops-recovery.test.ts',
      'test/monitor/recovering-watchdog.test.ts',
      'test/monitor/recovery-coordinator-deploy-lock.test.ts',
      'test/monitor/recovery-coordinator-partial-failure.test.ts',
      'test/monitor/project-health-monitor.test.ts',
      'test/monitor/project-state-manager.test.ts',
      'test/pipeline/approval-gate.test.ts',
      'test/pipeline/auto-recovery-llm-down.test.ts',
      'test/pipeline/cascade-isolation.test.ts',
      'test/pipeline/deploy-lock-session-propagation.test.ts',
      'test/pipeline/mutation-policy.test.ts',
      'test/pipeline/readiness-gate.test.ts',
      'test/tools/deploy-lock-mcp-tools.test.ts',
      'test/tools/image-schema.test.ts',
      'test/tools/monitoring.test.ts',
      'test/tools/platform-actions.test.ts',
      'test/tools/platform-integration.test.ts',
      'test/tools/platform-read.test.ts',
      'test/tools/platform-registration.test.ts',
      'test/tools/project-name-validation.test.ts',
      'test/tools/project-ops-reconcile.test.ts',
      'test/tools/project-ops-restart.test.ts',
      'test/tools/registry-critical-tools.test.ts',
      'test/tools/server-tools.test.ts',
    ],
    exclude: [
      'e2e/**',
      'web/**',
      'test/manual-qa/**',
      // Pre-Postgres SQLite migration replay suites are archived out of the
      // release gate until they are replaced with Postgres-backed tests.
      'test/db/migration-*.test.ts',
      'test/pipeline/docker/**',
      'test/docker.test.ts',
      'test/network-service-integration.test.ts',
      'test/pipeline/image-deploy-e2e.test.ts',
    ],
    setupFiles: ['test/setup-release.ts'],
    testTimeout: 15_000,
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'web/src'),
      'lucide-react': path.resolve(__dirname, 'test/mocks/lucide-react.ts'),
    },
  },
});
