import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { basename, join, relative } from 'node:path';

import { createModuleLogger } from '../lib/logger.js';
import { generateText } from 'ai';
import type { LanguageModel } from 'ai';
import type { ChatMessage } from '../llm/index.js';
import { withTracking } from '../llm/tracking-middleware.js';

const log = createModuleLogger('auto-detect');

const MAX_TREE_ENTRIES = 50;
const MAX_TREE_DEPTH = 2;
const MAX_PREVIEW_LINES = 30;

export interface AutoDetectResult {
  generated: boolean;
  type: 'dockerfile' | 'compose';
  content: string;
  explanation: string;
}

export class AutoDetector {
  constructor(private readonly model: LanguageModel | null) {}

  collectContext(projectPath: string): string {
    const sections: string[] = [];

    sections.push('## File Tree (depth<=2, max 50 entries)');
    const tree = this.collectTree(projectPath);
    sections.push(
      tree.length > 0 ? tree.map((entry) => `- ${entry}`).join('\n') : '- (no entries found)',
    );

    const packageJsonPath = join(projectPath, 'package.json');
    if (existsSync(packageJsonPath)) {
      sections.push('## package.json summary');
      sections.push(this.readPackageJsonSummary(packageJsonPath));
    }

    const requirementsPath = join(projectPath, 'requirements.txt');
    if (existsSync(requirementsPath)) {
      sections.push('## requirements.txt');
      sections.push(this.readTextPreview(requirementsPath, 120));
    }

    const pipfilePath = join(projectPath, 'Pipfile');
    if (existsSync(pipfilePath)) {
      sections.push('## Pipfile');
      sections.push(this.readTextPreview(pipfilePath, 120));
    }

    const goModPath = join(projectPath, 'go.mod');
    if (existsSync(goModPath)) {
      sections.push('## go.mod');
      sections.push(this.readTextPreview(goModPath, 120));
    }

    const cargoTomlPath = join(projectPath, 'Cargo.toml');
    if (existsSync(cargoTomlPath)) {
      sections.push('## Cargo.toml');
      sections.push(this.readTextPreview(cargoTomlPath, 120));
    }

    const pomXmlPath = join(projectPath, 'pom.xml');
    if (existsSync(pomXmlPath)) {
      sections.push('## pom.xml (first 30 lines)');
      sections.push(this.readTextPreview(pomXmlPath, MAX_PREVIEW_LINES));
    }

    const buildGradlePath = join(projectPath, 'build.gradle');
    if (existsSync(buildGradlePath)) {
      sections.push('## build.gradle (first 30 lines)');
      sections.push(this.readTextPreview(buildGradlePath, MAX_PREVIEW_LINES));
    }

    const buildGradleKtsPath = join(projectPath, 'build.gradle.kts');
    if (existsSync(buildGradleKtsPath)) {
      sections.push('## build.gradle.kts (first 30 lines)');
      sections.push(this.readTextPreview(buildGradleKtsPath, MAX_PREVIEW_LINES));
    }

    for (const versionFile of ['.nvmrc', '.node-version', '.python-version']) {
      const versionFilePath = join(projectPath, versionFile);
      if (existsSync(versionFilePath)) {
        sections.push(`## ${versionFile}`);
        sections.push(this.readTextPreview(versionFilePath, 10));
      }
    }

    const procfiles = this.collectProcfiles(projectPath);
    for (const procfile of procfiles) {
      sections.push(`## ${procfile}`);
      sections.push(this.readTextPreview(join(projectPath, procfile), 60));
    }

    return sections.join('\n\n');
  }

  async generateDockerfile(projectPath: string): Promise<AutoDetectResult | null> {
    const activeModel = this.model;
    if (!activeModel) {
      return null;
    }

    try {
      const context = this.collectContext(projectPath);

      const messages: ChatMessage[] = [
        {
          role: 'system',
          content:
            'You are an expert DevOps engineer. Based on the project structure below, generate a production-ready Dockerfile. Output ONLY the Dockerfile content, no explanation, no markdown fences.',
        },
        {
          role: 'user',
          content: `Project path: ${projectPath}\n\n${context}`,
        },
      ];

      const response = await withTracking({ actionType: 'auto_detect', source: 'auto' }, () =>
        generateText({
          model: activeModel,
          messages: messages.map((m) => ({
            role: m.role,
            content: m.content,
          })),
        }),
      );
      const content = this.extractDockerfileContent(response.text);
      if (!content) {
        return null;
      }

      return {
        generated: true,
        type: 'dockerfile',
        content,
        explanation: 'Dockerfile generated by LLM using detected project context.',
      };
    } catch (err: unknown) {
      log.warn({ err }, 'LLM auto-detection failed; returning null');
      return null;
    }
  }

  private collectTree(projectPath: string): string[] {
    const entries: string[] = [];
    const queue: Array<{ absPath: string; depth: number }> = [{ absPath: projectPath, depth: 0 }];
    const skippedDirs = new Set(['.git', 'node_modules', '.venv', 'venv', 'dist', 'build']);

    while (queue.length > 0 && entries.length < MAX_TREE_ENTRIES) {
      const current = queue.shift();
      if (!current) {
        break;
      }

      let dirents: Array<{ name: string; isDirectory(): boolean }>;
      try {
        dirents = readdirSync(current.absPath, { withFileTypes: true });
      } catch (_err) {
        continue;
      }

      for (const dirent of dirents.sort((a, b) => a.name.localeCompare(b.name))) {
        if (entries.length >= MAX_TREE_ENTRIES) {
          break;
        }

        const absPath = join(current.absPath, dirent.name);
        const relPath = relative(projectPath, absPath);
        const isDirectory = dirent.isDirectory();
        entries.push(isDirectory ? `${relPath}/` : relPath);

        if (isDirectory && current.depth < MAX_TREE_DEPTH && !skippedDirs.has(dirent.name)) {
          queue.push({ absPath, depth: current.depth + 1 });
        }
      }
    }

    return entries;
  }

  private readPackageJsonSummary(packageJsonPath: string): string {
    try {
      const raw = readFileSync(packageJsonPath, 'utf8');
      const parsed: unknown = JSON.parse(raw);
      if (!this.isRecord(parsed)) {
        return '(failed to parse package.json)';
      }

      const scripts = this.pickStringRecord(parsed.scripts);
      const dependencies = this.pickStringRecord(parsed.dependencies);
      const devDependencies = this.pickStringRecord(parsed.devDependencies);
      const engines = this.pickStringRecord(parsed.engines);

      const lines: string[] = [];
      lines.push(`name: ${this.readString(parsed.name) ?? '(unknown)'}`);
      lines.push(`scripts: ${JSON.stringify(scripts, null, 2)}`);
      lines.push(`dependencies: ${JSON.stringify(this.sliceRecord(dependencies, 30), null, 2)}`);
      lines.push(
        `devDependencies: ${JSON.stringify(this.sliceRecord(devDependencies, 30), null, 2)}`,
      );
      lines.push(`engines: ${JSON.stringify(engines, null, 2)}`);
      return lines.join('\n');
    } catch (err: unknown) {
      log.debug({ err }, 'Failed to read package.json summary');
      return '(failed to parse package.json)';
    }
  }

  private readTextPreview(filePath: string, maxLines: number): string {
    try {
      const raw = readFileSync(filePath, 'utf8');
      const lines = raw.split(/\r?\n/);
      const preview = lines.slice(0, maxLines).join('\n').trim();
      return preview.length > 0 ? preview : '(empty)';
    } catch (err: unknown) {
      log.debug({ err, filePath }, 'Failed to read file preview');
      return '(failed to read)';
    }
  }

  private collectProcfiles(projectPath: string): string[] {
    const procfiles: string[] = [];
    const queue: Array<{ absPath: string; depth: number }> = [{ absPath: projectPath, depth: 0 }];

    while (queue.length > 0) {
      const current = queue.shift();
      if (!current) {
        break;
      }

      let dirents: Array<{ name: string; isDirectory(): boolean; isFile(): boolean }>;
      try {
        dirents = readdirSync(current.absPath, { withFileTypes: true });
      } catch (_err) {
        continue;
      }

      for (const dirent of dirents) {
        const absPath = join(current.absPath, dirent.name);
        if (dirent.isFile() && basename(dirent.name).startsWith('Procfile')) {
          procfiles.push(relative(projectPath, absPath));
        }
        if (dirent.isDirectory() && current.depth < MAX_TREE_DEPTH) {
          queue.push({ absPath, depth: current.depth + 1 });
        }
      }
    }

    return procfiles.sort((a, b) => a.localeCompare(b));
  }

  private extractDockerfileContent(raw: string): string {
    const trimmed = raw.trim();
    if (!trimmed) {
      return '';
    }

    const fencedMatch = trimmed.match(/^```(?:dockerfile|Dockerfile)?\s*\n([\s\S]*?)\n```$/);
    if (fencedMatch && fencedMatch[1]) {
      return fencedMatch[1].trim();
    }

    return trimmed
      .replace(/^```(?:dockerfile|Dockerfile)?\s*/g, '')
      .replace(/\s*```$/g, '')
      .trim();
  }

  private isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
  }

  private readString(value: unknown): string | null {
    return typeof value === 'string' ? value : null;
  }

  private pickStringRecord(value: unknown): Record<string, string> {
    if (!this.isRecord(value)) {
      return {};
    }

    const out: Record<string, string> = {};
    for (const [key, entryValue] of Object.entries(value)) {
      if (typeof entryValue === 'string') {
        out[key] = entryValue;
      }
    }

    return out;
  }

  private sliceRecord(record: Record<string, string>, maxEntries: number): Record<string, string> {
    return Object.fromEntries(Object.entries(record).slice(0, maxEntries));
  }
}

/**
 * Standalone project context collector for use outside AutoDetector.
 * Collects file tree, package manifests, and version files from a project directory.
 */
export function collectProjectContext(projectPath: string): string {
  const detector = new AutoDetector(null);
  return detector.collectContext(projectPath);
}
