import type { EnvManager } from './env.js';
import { filterBuildTimeVars } from './build-args.js';

export interface ResolveEnvParams {
  projectId: string;
  serviceId?: string;
  environmentId?: string;
  inlineEnvVars?: Record<string, string>;
  autoEnvVars?: Record<string, string>;
  serviceEnvVars?: Record<string, string>;
  runtimeEnvVars?: Record<string, string>;
}

/**
 * Resolves environment variables using explicit 7-layer precedence.
 *
 * Lowest to highest:
 * 1) autoEnvVars generated by deploy-plan managed-service suggestions
 * 2) global secrets
 * 3) project shared vars
 * 4) project environment vars (including the v0.1 production-base compatibility layer)
 * 5) service shared vars
 * 6) service environment vars
 * 7) serviceEnvVars / inlineEnvVars supplied by the deploy request
 * 8) runtimeEnvVars protected by OpenLander runtime wiring
 */
export async function resolveEnvVars(
  params: ResolveEnvParams,
  deps: { env: EnvManager },
): Promise<Record<string, string>> {
  const env = deps.env as EnvManager & {
    getAllWithInheritance?: EnvManager['getAllWithInheritance'];
  };
  const autoEnvVars = params.autoEnvVars ?? {};
  const globalSecrets = await deps.env.getGlobalSecrets();
  const projectEnvVars = await resolveProjectEnvVars(params, { env });
  const serviceSharedEnvVars = params.serviceId
    ? await deps.env.getAllForService(params.projectId, params.serviceId)
    : {};
  const serviceEnvironmentEnvVars =
    params.serviceId && params.environmentId
      ? await deps.env.getAllForService(params.projectId, params.serviceId, params.environmentId)
      : {};

  const serviceEnvVars = params.serviceEnvVars ?? {};
  const inlineEnvVars = params.inlineEnvVars ?? {};
  const runtimeEnvVars = params.runtimeEnvVars ?? {};

  return {
    ...autoEnvVars,
    ...globalSecrets,
    ...projectEnvVars,
    ...serviceSharedEnvVars,
    ...serviceEnvironmentEnvVars,
    ...serviceEnvVars,
    ...inlineEnvVars,
    ...runtimeEnvVars,
  };
}

async function resolveProjectEnvVars(
  params: ResolveEnvParams,
  deps: {
    env: EnvManager & {
      getAllWithInheritance?: EnvManager['getAllWithInheritance'];
    };
  },
): Promise<Record<string, string>> {
  if (params.environmentId === undefined) {
    return await deps.env.getAll(params.projectId);
  }

  if (typeof deps.env.getAllWithInheritance === 'function') {
    return await deps.env.getAllWithInheritance(params.projectId, params.environmentId);
  }

  return {
    ...(await deps.env.getAll(params.projectId)),
    ...(await deps.env.getAll(params.projectId, params.environmentId)),
  };
}

/**
 * Resolves env vars, then keeps only build-time variables.
 */
export async function resolveEnvVarsForBuild(
  params: ResolveEnvParams,
  deps: { env: EnvManager },
): Promise<Record<string, string>> {
  return filterBuildTimeVars(await resolveEnvVars(params, deps));
}
