import type {
  MigrationReadinessCheck,
  MigrationService,
  ProjectMigrationSnapshotV1,
} from './types.js';

function text(value: string | number | null | undefined): string {
  if (value === null || value === undefined || value === '') return '—';
  return String(value)
    .replace(/\|/g, '\\|')
    .replace(/[\r\n]+/g, ' ');
}

function checked(value: boolean): string {
  return value ? 'yes' : 'no';
}

function serviceCategory(service: MigrationService): string {
  switch (service.kind) {
    case 'compose':
    case 'compose-child':
      return 'Compose';
    case 'postgres':
    case 'mysql':
    case 'mongo':
    case 'neo4j':
      return 'Database';
    case 'redis':
      return 'Cache';
    case 'minio':
      return 'Storage';
    default:
      return 'Application';
  }
}

function checkList(checks: MigrationReadinessCheck[]): string[] {
  if (checks.length === 0) return ['- No readiness checks were emitted.'];
  return checks.map(
    (check) =>
      `- **${check.level.toUpperCase()} · ${text(check.code)}**${
        check.service_id ? ` (${text(check.service_id)})` : ''
      }: ${text(check.message)}`,
  );
}

export function renderProjectMigrationMarkdown(snapshot: ProjectMigrationSnapshotV1): string {
  const deployableServices = snapshot.services.filter((service) =>
    ['git', 'image', 'compose', 'compose-child'].includes(service.kind),
  );
  const managedServices = snapshot.services.filter((service) =>
    ['postgres', 'mysql', 'redis', 'mongo', 'neo4j', 'minio'].includes(service.kind),
  );
  const limitations = snapshot.readiness.checks.filter((check) => check.level !== 'pass');

  const lines: string[] = [
    `# Migration plan: ${text(snapshot.project.display_name)}`,
    '',
    `Generated by OpenLander at \`${snapshot.generated_at}\` using schema \`${snapshot.schema_version}\`.`,
    '',
    '## 1. Project overview and readiness',
    '',
    `- Project ID: \`${text(snapshot.project.id)}\``,
    `- Project slug: \`${text(snapshot.project.name)}\``,
    `- Readiness: **${snapshot.readiness.status}**`,
    `- Runtime inspection: **${snapshot.runtime_inspection.status}**`,
    '- This package does not create cloud resources, copy data, or change DNS.',
    '',
    ...checkList(snapshot.readiness.checks),
    '',
    '## 2. Applications and source',
    '',
    '| Type | Name | Kind | Source | Revision / image ID | Runtime |',
    '| --- | --- | --- | --- | --- | --- |',
    ...deployableServices.map((service) => {
      const source =
        service.source.repo_url ?? service.source.image_reference ?? service.source.type;
      const revision = service.last_deploy?.commit_sha ?? service.source.image_id;
      return `| ${serviceCategory(service)} | ${text(service.name)} | ${text(service.kind)} | ${text(source)} | ${text(revision)} | ${text(service.runtime.status)} |`;
    }),
    ...(deployableServices.length === 0
      ? ['| — | No Application or Compose resource found | — | — | — | — |']
      : []),
    '',
    '## 3. Database, Cache, and Storage resources',
    '',
    '| Type | Name | Kind | Image | Ownership | Status |',
    '| --- | --- | --- | --- | --- | --- |',
    ...managedServices.map(
      (service) =>
        `| ${serviceCategory(service)} | ${text(service.name)} | ${text(service.kind)} | ${text(service.source.image_reference)} | ${text(service.ownership)} | ${text(service.runtime.status)} |`,
    ),
    ...(managedServices.length === 0
      ? ['| — | No managed data resource found | — | — | — | — |']
      : []),
    '',
    '## 4. Service dependencies',
    '',
    '| Consumer service | Provider service | Environment | Injected env keys |',
    '| --- | --- | --- | --- |',
    ...snapshot.service_connections.map(
      (connection) =>
        `| ${text(connection.service_id_consumer)} | ${text(connection.service_id_provider)} | ${text(connection.environment_id)} | ${text(connection.auto_injected_env_keys.join(', '))} |`,
    ),
    ...(snapshot.service_connections.length === 0
      ? ['| — | No formal service connections found | — | — |']
      : []),
    '',
    '## 5. Persistent volumes and data transfer',
    '',
    '| Type | Name / source | Destination | Size (bytes) | Services | Read only |',
    '| --- | --- | --- | ---: | --- | --- |',
    ...snapshot.volumes.map(
      (volume) =>
        `| ${text(volume.type)} | ${text(volume.name ?? volume.source)} | ${text(volume.destination)} | ${text(volume.size_bytes)} | ${text(volume.service_ids.join(', '))} | ${checked(volume.read_only)} |`,
    ),
    ...(snapshot.volumes.length === 0
      ? ['| — | No persistent mounts observed | — | — | — | — |']
      : []),
    '',
    'OpenLander volume backups are runtime snapshots, not guaranteed portable logical exports. Plan explicit logical export/import for every stateful data resource.',
    '',
    '## 6. Environment variables and secret re-entry',
    '',
    '| Key | Scope | Service | Environment | Sensitive | Public |',
    '| --- | --- | --- | --- | --- | --- |',
    ...snapshot.environment_variables.map(
      (variable) =>
        `| ${text(variable.key)} | ${text(variable.scope)} | ${text(variable.service_id)} | ${text(variable.environment_id)} | ${checked(variable.sensitive)} | ${checked(variable.public)} |`,
    ),
    ...(snapshot.environment_variables.length === 0
      ? ['| — | No project environment-variable metadata found | — | — | — | — |']
      : []),
    '',
    'Secret values and all environment-variable values are intentionally excluded. Re-enter required values through the destination platform’s secret/configuration system.',
    '',
    ...snapshot.secret_files.map(
      (file) =>
        `- Secret file \`${text(file.filename)}\` must be recreated at \`${text(file.mount_path)}\`.`,
    ),
    ...(snapshot.secret_files.length === 0
      ? ['- No project-scoped secret file metadata found.']
      : []),
    '',
    '## 7. Domains and cutover',
    '',
    '| Domain | Path | Service | Target port | TLS | Status |',
    '| --- | --- | --- | ---: | --- | --- |',
    ...snapshot.domain_routes.map(
      (route) =>
        `| ${text(route.domain)} | ${text(route.path_prefix)} | ${text(route.service_id)} | ${text(route.target_port)} | ${checked(route.tls_enabled === true)} | ${text(route.status)} |`,
    ),
    ...(snapshot.domain_routes.length === 0
      ? ['| — | No custom domain routes found | — | — | — | — |']
      : []),
    '',
    '## 8. Provider-neutral migration sequence',
    '',
    '1. Select a destination runtime for each Application and Compose workload.',
    '2. Provision Database, Cache, Storage, and persistent-volume destinations independently.',
    '3. Recreate environment variables and secrets without copying values through this package.',
    '4. Export and import stateful data with resource-specific logical tooling.',
    '5. Deploy workloads using pinned commits or immutable image digests.',
    '6. Validate health checks and internal Service Connections before public traffic.',
    '7. Move custom domains and DNS only after destination verification.',
    '8. Keep the OpenLander deployment available until rollback is no longer required.',
    '',
    '## 9. Unknowns and limitations',
    '',
    ...(limitations.length > 0
      ? limitations.map((check) => `- **${text(check.code)}:** ${text(check.message)}`)
      : ['- No blockers or warnings were detected from the available metadata.']),
    '',
    'This document does not inventory database schemas/tables, Redis keys, or object-storage buckets/objects, and it does not contain data payloads or credentials.',
    '',
  ];

  return lines.join('\n');
}
