import type { MigrationTargetPlan, ProjectMigrationTargetComparisonV1 } from './target-types.js';

function text(value: string | number | null | undefined): string {
  if (value === null || value === undefined || value === '') return '—';
  return String(value)
    .replace(/\|/g, '\\|')
    .replace(/[\r\n]+/g, ' ');
}

function renderTarget(target: MigrationTargetPlan): string[] {
  return [
    `## ${text(target.display_name)}`,
    '',
    `- Assessment: **${target.status}**`,
    `- Mapped services: ${String(target.summary.mapped_service_count)}`,
    `- Mapped volumes: ${String(target.summary.mapped_volume_count)}`,
    `- Manual reviews: ${String(target.summary.manual_review_count)}`,
    '',
    '### Service mappings',
    '',
    '| Source | Kind | Ownership | Target | Method | Confidence |',
    '| --- | --- | --- | --- | --- | --- |',
    ...target.resource_mappings.map(
      (mapping) =>
        `| ${text(mapping.source_service_name)} | ${text(mapping.source_kind)} | ${text(mapping.source_ownership)} | ${text(mapping.target_resource_name)} | ${text(mapping.migration_method)} | ${text(mapping.confidence)} |`,
    ),
    ...(target.resource_mappings.length === 0
      ? ['| — | No source services found | — | — | — | — |']
      : []),
    '',
    '### Persistent data mappings',
    '',
    '| Source | Type | Target | Method | Confidence |',
    '| --- | --- | --- | --- | --- |',
    ...target.volume_mappings.map(
      (mapping) =>
        `| ${text(mapping.source_volume_name)} | ${text(mapping.source_type)} | ${text(mapping.target_resource_name)} | ${text(mapping.migration_method)} | ${text(mapping.confidence)} |`,
    ),
    ...(target.volume_mappings.length === 0
      ? ['| — | No persistent mounts observed | — | — | — |']
      : []),
    '',
    '### Supporting resources',
    '',
    ...target.supporting_resources.map(
      (resource) =>
        `- **${text(resource.display_name)}** (${resource.required ? 'required' : 'optional'}): ${text(resource.reason)}`,
    ),
    ...(target.supporting_resources.length === 0
      ? ['- No supporting cloud resources inferred.']
      : []),
    '',
    '### Findings',
    '',
    ...target.findings.map(
      (finding) =>
        `- **${text(finding.level.toUpperCase())} · ${text(finding.code)}**${
          finding.service_id ? ` (${text(finding.service_id)})` : ''
        }: ${text(finding.message)}`,
    ),
    ...(target.findings.length === 0 ? ['- No target-specific findings.'] : []),
    '',
    '### Official references',
    '',
    ...target.references.map((reference) => `- [${text(reference.title)}](${reference.url})`),
    '',
  ];
}

export function renderProjectMigrationTargetMarkdown(
  comparison: ProjectMigrationTargetComparisonV1,
): string {
  const lines: string[] = [
    `# Migration target comparison: ${text(comparison.project.display_name)}`,
    '',
    `Generated by OpenLander at \`${comparison.generated_at}\` using schema \`${comparison.schema_version}\`.`,
    '',
    'This assessment does not query cloud accounts or pricing, create resources, copy data, or change DNS.',
    '',
    '## Comparison summary',
    '',
    '| Target | Assessment | Services | Volumes | Manual reviews | Blockers |',
    '| --- | --- | ---: | ---: | ---: | ---: |',
    ...comparison.targets.map(
      (target) =>
        `| ${text(target.display_name)} | ${text(target.status)} | ${String(target.summary.mapped_service_count)} | ${String(target.summary.mapped_volume_count)} | ${String(target.summary.manual_review_count)} | ${String(target.summary.blocker_count)} |`,
    ),
    '',
    ...comparison.targets.flatMap(renderTarget),
    '## Cross-target decision checklist',
    '',
    '1. Resolve provider-neutral blockers before choosing either target.',
    '2. Validate every low-confidence Compose, MongoDB, MinIO, and bind-mount mapping.',
    '3. Compare region, availability, quota, IAM, network, and pricing in the destination account.',
    '4. Test logical data export/import and application compatibility before cutover.',
    '5. Provision only after a human approves one reviewed target plan.',
    '',
  ];
  return lines.join('\n');
}
