import { existsSync, readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import {
  DRIZZLE_DIR,
  activeMigrationSqlFiles,
  migrationSqlPath,
  quotedIdentifiers,
  readMigrationJournal,
  readMigrationSqlInJournalOrder,
  splitMigrationStatements,
  staticTableShapeFromSql,
  type StaticTableShape,
} from './postgres-migration-helpers.js';

const SQLITE_ONLY_PATTERNS: Array<{ label: string; pattern: RegExp }> = [
  { label: 'PRAGMA', pattern: /\bPRAGMA\b/i },
  { label: 'sqlite_master', pattern: /\bsqlite_master\b/i },
  { label: 'AUTOINCREMENT', pattern: /\bAUTOINCREMENT\b/i },
  { label: 'INSERT OR IGNORE/REPLACE', pattern: /\bINSERT\s+OR\s+(?:IGNORE|REPLACE)\b/i },
  { label: 'WITHOUT ROWID', pattern: /\bWITHOUT\s+ROWID\b/i },
  { label: 'SQLite datetime()', pattern: /\bdatetime\s*\(/i },
  { label: 'SQLite strftime()', pattern: /\bstrftime\s*\(/i },
  { label: 'SQLite json_extract()', pattern: /\bjson_extract\s*\(/i },
  { label: 'SQLite RAISE()', pattern: /\bRAISE\s*\(/i },
  { label: 'backtick identifier quoting', pattern: /`[^`]+`/ },
];

function validateForeignKeys(sql: string, tables: StaticTableShape): string[] {
  const failures: string[] = [];
  const fkPattern =
    /ALTER TABLE\s+"([^"]+)"\s+ADD CONSTRAINT\s+"([^"]+)"\s+FOREIGN KEY\s+\(([^)]*)\)\s+REFERENCES\s+(?:"public"\.)?"([^"]+)"\s*\(([^)]*)\)/gi;

  for (const match of sql.matchAll(fkPattern)) {
    const sourceTable = match[1]!;
    const constraintName = match[2]!;
    const sourceColumns = quotedIdentifiers(match[3]!);
    const targetTable = match[4]!;
    const targetColumns = quotedIdentifiers(match[5]!);

    validateKnownColumns(tables, failures, constraintName, sourceTable, sourceColumns);
    validateKnownColumns(tables, failures, constraintName, targetTable, targetColumns);
  }

  return failures;
}

function validateIndexes(sql: string, tables: StaticTableShape): string[] {
  const failures: string[] = [];
  const indexPattern =
    /CREATE\s+(?:UNIQUE\s+)?INDEX\s+"([^"]+)"\s+ON\s+"([^"]+)"\s+USING\s+\w+\s+\(([^;]*)\);/gi;

  for (const match of sql.matchAll(indexPattern)) {
    const indexName = match[1]!;
    const tableName = match[2]!;
    const columnsSegment = match[3]!;
    const columns = quotedIdentifiers(columnsSegment);

    // Expression indexes can contain quoted identifiers inside expressions.
    // This gate validates plain column-list indexes generated by Drizzle.
    const nonIdentifierText = columnsSegment.replace(/"[^"]+"/g, '').replace(/[,\s]/g, '');
    if (nonIdentifierText.length > 0) {
      continue;
    }

    validateKnownColumns(tables, failures, indexName, tableName, columns);
  }

  return failures;
}

function validateKnownColumns(
  tables: StaticTableShape,
  failures: string[],
  objectName: string,
  tableName: string,
  columnNames: string[],
): void {
  const tableColumns = tables.get(tableName);
  if (!tableColumns) {
    failures.push(`${objectName}: table '${tableName}' is not created by active migrations`);
    return;
  }

  for (const columnName of columnNames) {
    if (!tableColumns.has(columnName)) {
      failures.push(`${objectName}: column '${tableName}.${columnName}' is not created`);
    }
  }
}

describe('Postgres migration sanity gate', () => {
  it('uses a Postgres Drizzle journal and every active SQL file is journaled', () => {
    const journal = readMigrationJournal();
    const expectedSqlFiles = journal.entries.map((entry) => `${entry.tag}.sql`).sort();

    expect(journal.dialect).toBe('postgresql');
    expect(journal.entries.length).toBeGreaterThan(0);
    expect(journal.entries.map((entry) => entry.idx)).toEqual(
      journal.entries.map((_, index) => index),
    );
    expect(activeMigrationSqlFiles()).toEqual(expectedSqlFiles);

    for (const entry of journal.entries) {
      expect(existsSync(migrationSqlPath(entry.tag))).toBe(true);
      expect(entry.breakpoints).toBe(true);
    }
  });

  it('contains only Postgres migration SQL, with no archived SQLite syntax in active files', () => {
    const failures: string[] = [];

    for (const fileName of activeMigrationSqlFiles()) {
      const sql = readFileSync(`${DRIZZLE_DIR}/${fileName}`, 'utf8');
      for (const { label, pattern } of SQLITE_ONLY_PATTERNS) {
        if (pattern.test(sql)) {
          failures.push(`${fileName}: contains ${label}`);
        }
      }
    }

    expect(failures).toEqual([]);
  });

  it('keeps migration statements split on Drizzle breakpoints with semicolon terminators', () => {
    const failures: string[] = [];

    for (const fileName of activeMigrationSqlFiles()) {
      const sql = readFileSync(`${DRIZZLE_DIR}/${fileName}`, 'utf8');
      const statements = splitMigrationStatements(sql);

      if (statements.length === 0) {
        failures.push(`${fileName}: contains no statements`);
      }

      statements.forEach((statement, index) => {
        if (!statement.endsWith(';')) {
          failures.push(`${fileName}: statement ${index + 1} is missing a semicolon`);
        }
      });
    }

    expect(failures).toEqual([]);
  });

  it('does not reference missing tables or columns from migration FKs and indexes', () => {
    const sql = readMigrationSqlInJournalOrder();
    const tables = staticTableShapeFromSql(sql);
    const failures = [...validateForeignKeys(sql, tables), ...validateIndexes(sql, tables)];

    expect(failures).toEqual([]);
  });

  it('keeps v0.1 baseline as a single fresh-install migration with merged critical tables', () => {
    const journal = readMigrationJournal();
    const sql = readMigrationSqlInJournalOrder();

    expect(journal.entries.map((entry) => entry.tag)).toEqual(['0000_v0_1_initial']);
    expect(activeMigrationSqlFiles()).toEqual(['0000_v0_1_initial.sql']);
    expect(sql).toContain('CREATE TABLE "pat_tokens"');
    expect(sql).toContain('"active_scope_project_id" text');
    expect(sql).toContain('CREATE TABLE "domain_mappings"');
    expect(sql).toContain('"target_port" integer');
    expect(sql).toContain('CONSTRAINT "domain_mappings_target_port_check"');
  });

  it('fails fast on pre-0.1 migration histories instead of silently replaying the reset baseline', () => {
    const source = readFileSync('src/db/index.ts', 'utf8');

    expect(source).toContain('DATABASE_BASELINE_RESET_REQUIRED');
    expect(source).toContain('public.migration_0009_audit');
    expect(source).toContain('drizzle.__drizzle_migrations');
    expect(source).toContain('drizzleMigrationCount > 1');
  });
});
